"""
Wiki routes — person biographical pages generated by LLM.

Pages:
  GET  /wiki/people/{person_id}              — rendered wiki page
  POST /api/wiki/generate/person/{person_id} — trigger background generation
  GET  /api/wiki/status/person/{person_id}   — poll status
  GET  /api/wiki/people                      — list all persons with wiki status
"""
from __future__ import annotations

import logging
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from app.background import spawn
from app.database import get_db
from app.models import (
    KinMembership,
    Person,
    PersonAlias,
    RelationshipEdge,
    Response,
    ResponsePerson,
    WikiArticle,
)
from app.routes_shared import templates
from app.services.people_acl import person_visibility_filter, visible_group_ids
from app.services.wiki_generator import generate_person_wiki, _invert_rel
from app.utils import require_authenticated_user, require_authenticated_html_user

router = APIRouter()
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

async def _get_visible_person(
    db: AsyncSession, person_id: int, user_id: int
) -> Person:
    """Fetch a person if the user has visibility, else 404."""
    group_ids = await visible_group_ids(db, user_id)
    p = await db.scalar(
        select(Person)
        .where(Person.id == person_id)
        .where(person_visibility_filter(user_id, group_ids))
    )
    if not p:
        raise HTTPException(404, "Person not found")
    return p


async def _load_wiki_context(db: AsyncSession, person: Person, user_id: int) -> dict:
    """Assemble all data needed by the wiki template."""
    person_id = person.id

    # Aliases
    aliases = (
        await db.execute(
            select(PersonAlias.alias).where(PersonAlias.person_id == person_id)
        )
    ).scalars().all()

    # Relationships
    group_ids = await visible_group_ids(db, user_id)
    if group_ids:
        edge_scope = or_(
            RelationshipEdge.user_id == user_id,
            RelationshipEdge.group_id.in_(group_ids),
        )
    else:
        edge_scope = RelationshipEdge.user_id == user_id

    DstPerson = aliased(Person)
    SrcPerson = aliased(Person)

    src_rows = (
        await db.execute(
            select(RelationshipEdge.rel_type, RelationshipEdge.id, DstPerson.id, DstPerson.display_name)
            .join(DstPerson, DstPerson.id == RelationshipEdge.dst_id)
            .where(RelationshipEdge.src_id == person_id)
            .where(edge_scope)
        )
    ).all()

    dst_rows = (
        await db.execute(
            select(RelationshipEdge.rel_type, RelationshipEdge.id, SrcPerson.id, SrcPerson.display_name)
            .join(SrcPerson, SrcPerson.id == RelationshipEdge.src_id)
            .where(RelationshipEdge.dst_id == person_id)
            .where(edge_scope)
        )
    ).all()

    edges: list[dict] = []
    for rel_type, edge_id, other_id, other_name in src_rows:
        edges.append({"label": rel_type.replace("-", " "), "person_id": other_id, "name": other_name})
    for rel_type, edge_id, other_id, other_name in dst_rows:
        edges.append({"label": _invert_rel(rel_type).replace("-", " "), "person_id": other_id, "name": other_name})

    # Story mentions (for the sidebar)
    mention_rows = (
        await db.execute(
            select(Response.id, Response.title, Response.created_at)
            .join(ResponsePerson, ResponsePerson.response_id == Response.id)
            .where(ResponsePerson.person_id == person_id)
            .where(Response.user_id == user_id)
            .order_by(Response.created_at.desc())
            .limit(20)
        )
    ).all()
    mentions = [
        {"response_id": rid, "title": title or "Untitled", "created_at": created_at}
        for rid, title, created_at in mention_rows
    ]

    # Existing wiki article
    article = await db.scalar(
        select(WikiArticle).where(
            WikiArticle.entity_type == "person",
            WikiArticle.entity_id == person_id,
            WikiArticle.user_id == user_id,
        )
    )

    # Photo URL
    photo_url = None
    if person.photo_url:
        rel = (person.photo_url or "").lstrip("/").replace("\\", "/")
        if not rel.startswith("uploads/"):
            rel = f"uploads/{rel}"
        photo_url = f"/media/auth/{rel}"

    return {
        "person": person,
        "person_id": person_id,
        "display_name": person.display_name,
        "aliases": list(aliases),
        "birth_year": person.birth_year,
        "death_year": person.death_year,
        "notes": person.notes,
        "photo_url": photo_url,
        "edges": edges,
        "mentions": mentions,
        "article": article,
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@router.get("/wiki", response_class=HTMLResponse)
async def wiki_index(
    request: Request,
    user=Depends(require_authenticated_html_user),
    db: AsyncSession = Depends(get_db),
):
    people = await api_wiki_people_index.__wrapped__(user=user, db=db) \
        if hasattr(api_wiki_people_index, "__wrapped__") \
        else await _wiki_people_list(db, user.id)
    return templates.TemplateResponse(
        request,
        "wiki_index.html",
        {"user": user, "title": "Family Wiki", "people": people},
    )


async def _wiki_people_list(db: AsyncSession, user_id: int) -> list:
    group_ids = await visible_group_ids(db, user_id)
    persons = (
        await db.execute(
            select(Person).where(person_visibility_filter(user_id, group_ids))
        )
    ).scalars().all()
    articles = (
        await db.execute(
            select(WikiArticle).where(
                WikiArticle.entity_type == "person",
                WikiArticle.user_id == user_id,
            )
        )
    ).scalars().all()
    article_map = {a.entity_id: a for a in articles}
    out = []
    for p in sorted(persons, key=lambda x: (x.display_name or "").lower()):
        art = article_map.get(p.id)
        out.append(
            {
                "person_id": p.id,
                "display_name": p.display_name,
                "photo_url": p.photo_url,
                "birth_year": p.birth_year,
                "death_year": p.death_year,
                "wiki_status": art.status if art else "none",
                "wiki_generated_at": art.generated_at.isoformat() if art and art.generated_at else None,
            }
        )
    return out


@router.get("/wiki/people/{person_id}", response_class=HTMLResponse)
async def wiki_person_page(
    request: Request,
    person_id: int,
    user=Depends(require_authenticated_html_user),
    db: AsyncSession = Depends(get_db),
):
    person = await _get_visible_person(db, person_id, user.id)
    ctx = await _load_wiki_context(db, person, user.id)
    return templates.TemplateResponse(
        request,
        "wiki_person.html",
        {
            "user": user,
            "title": f"{ctx['display_name']} – Wiki",
            **ctx,
        },
    )


@router.post("/api/wiki/generate/person/{person_id}")
async def api_wiki_generate_person(
    person_id: int,
    user=Depends(require_authenticated_user),
    db: AsyncSession = Depends(get_db),
):
    # Visibility check
    await _get_visible_person(db, person_id, user.id)

    # Check if already generating
    existing = await db.scalar(
        select(WikiArticle).where(
            WikiArticle.entity_type == "person",
            WikiArticle.entity_id == person_id,
            WikiArticle.user_id == user.id,
        )
    )
    if existing and existing.status == "generating":
        return JSONResponse({"status": "generating", "message": "Already in progress"}, status_code=200)

    # Spawn background generation
    spawn(
        generate_person_wiki(person_id, user.id),
        name=f"wiki-person-{person_id}-user-{user.id}",
    )
    return JSONResponse({"status": "generating", "message": "Generation started"}, status_code=202)


@router.get("/api/wiki/status/person/{person_id}")
async def api_wiki_status_person(
    person_id: int,
    user=Depends(require_authenticated_user),
    db: AsyncSession = Depends(get_db),
):
    article = await db.scalar(
        select(WikiArticle).where(
            WikiArticle.entity_type == "person",
            WikiArticle.entity_id == person_id,
            WikiArticle.user_id == user.id,
        )
    )
    if not article:
        return {"status": "none", "generated_at": None, "source_count": None}
    return {
        "status": article.status,
        "generated_at": article.generated_at.isoformat() if article.generated_at else None,
        "source_count": article.source_count,
        "model_name": article.model_name,
        "error_msg": article.error_msg,
    }


@router.get("/api/wiki/people")
async def api_wiki_people_index(
    user=Depends(require_authenticated_user),
    db: AsyncSession = Depends(get_db),
):
    """Return all visible persons with their wiki article status."""
    return await _wiki_people_list(db, user.id)
